'use client'

import {
  createContext,
    useContext,
      useEffect,
        useMemo,
          useRef,
            useState,
              type ReactNode,
              } from 'react'
              
              export type Habit = {
                id: string
                  name: sting
                    detail: string
                      streak: number
                        done: boolean
                        }
                        
                        type StreakContextValue = {
                          habits: Habit[]
                            toggleHabit: (id: string) => boolean // returns true when a habit becomes completed
                              completedCount: number
                                totalCount: number
                                  bestStreak: num
                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                ...h,
                                                                                                                                                                                                                                                                          done: nextDone,
                                                                                                                                                                                                                                                                                    streak: nextDone ? h.streak + 1 : Math.max(0, h.streak - 1),
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                  }),
                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                          return becameComplete
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                              const value = useMemo<StreakContextValue>(() => {
                                                                                                                                                                                                                                                                                                                  const completedCount = habits.filter((h) => h.done).length
                                                                                                                                                                                                                                                                                                                      const bestStreak = habits.reduce((max, h) => Math.max(max, h.streak), 0)
                                                                                                                                                                                                                                                                                                                          const weeklyCompletion = [
                                                                                                                                                                                                                                                                                                                                { day: 'Mon', value: 80 },
                                                                                                                                                                                                                                                                                                                                      { day: 'Tue', value: 100 },
                                                                                                                                                                                                                                                                                                                                            { day: 'Wed', value: 60 },
                                                                                                                                                                                                                                                                                                                                                  { day: 'Thu', value: 100 },
                                                                                                                                                                                                                                                                                                                                                        { day: 'Fri', value: 40 },
                                                                                                                                                                                                                                                                                                                                                              { day: 'Sat', value: 90 },
                                                                                                                                                                                                                                                                                                                                                                    { day: 'Sun', value: Math.round((completedCount / habits.length) * 100) },
                                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                  habits,
                                                                                                                                                                                                                                                                                                                                                                                        toggleHabit,
                                                                                                                                                                                                                                                                                                                                                                                              completedCount,
                                                                                                                                                                                                                                                                                                                                                                                                    totalCount: habits.length,
                                                                                                                                                                                                                                                                                                                                                                                                          bestStreak,
                                                                                                                                                                                                                                                                                                                                                                                                                allComplete: completedCount === habits.length,
                                                                                                                                                                                                                                                                                                                                                                                                                      weeklyCompletion,
                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                            }, [habits])
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                              return <StreakContext.Provider value={value}>{children}</StreakContext.Provider>
                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                              export function useStreak() {
                                                                                                                                                                                                                                                                                                                                                                                                                                const ctx = useContext(StreakContext)
                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!ctx) throw new Error('useStreak must be used within a StreakProvider')
                                                                                                                                                                                                                                                                                                                                                                                                                                    return ctx
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                    '''use client'
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                    import { createContext, useContext, useState, ReactNode } from 'react'
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                    export type Habit = {
                                                                                                                                                                                                                                                                                                                                                                                                                                      id: string
                                                                                                                                                                                                                                                                                                                                                                                                                                        name: string
                                                                                                                                                                                                                                                                                                                                                                                                                                          description: string
                                                                                                                                                                                                                                                                                                                                                                                                                                            current: number
                                                                                                                                                                                                                                                                                                                                                                                                                                              target: number
                                                                                                                                                                                                                                                                                                                                                                                                                                                unit: string
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                type StreakContextType = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  habits: Habit[]
                                                                                                                                                                                                                                                                                                                                                                                                                                                    incrementHabit: (id: string) => void
                                                                                                                                                                                                                                                                                                                                                                                                                                                      decrementHabit: (id: string) => void
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const StreakContext = createContext<StreakContextType | undefined>(undefined)
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                      export function StreakProvider({ children }: { children: ReactNode }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Yahan humne naya 'current' aur 'target' logic add kiya hai
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const [habits, setHabits] = useState<Habit[]>([
                                                                                                                                                                                                                                                                                                                                                                                                                                                              { id: '1', name: 'Drink water', description: 'Hydration goal', current: 0, target: 2, unit: 'L' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { id: '2', name: 'Read a book', description: 'Daily learning', current: 0, target: 20, unit: 'Mins' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { id: '3', name: 'Morning workout', description: 'Activity', current: 0, target: 1, unit: 'Session' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const incrementHabit = (id: string) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setHabits((prev) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    prev.map((h) => (h.id === id && h.current < h.target ? { ...h, current: h.current + 1 } : h))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const decrementHabit = (id: string) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setHabits((prev) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      prev.map((h) => (h.id === id && h.current > 0 ? { ...h, current: h.current - 1 } : h))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <StreakContext.Provider value={{ habits, incrementHabit, decrementHabit }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {children}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </StreakContext.Provider>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export const useStreak = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const context = useContext(StreakContext)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!context) throw new Error('useStreak must be used within StreakProvider')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return context
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '